[package]
name = "jipher"
version = "0.1.0"
edition = "2024"

[dependencies]
combinations = "0.1.0"
regex = "1.11.1"
rayon = "1.10.0"
serde_json = "1.0.140"
zstd = "0.13"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
